apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rpa-mit-payment-generator
  description: The MIT payment generator service
  annotations:
    github.com/project-slug: defra/rpa-mit-payment-generator
    dev.azure.com/project: DEFRA-MIT
    dev.azure.com/build-definition: rpa-mit-payment-generator
    sonarqube.org/project-key: rpa-mit-payment-generator
    grafana/dashboard-selector: "folderTitle == 'Managed Prometheus'"
    backstage.io/kubernetes-id: rpa-mit-payment-generator
  links:
    - url: https://github.com/DEFRA/rpa-mit-payment-generator
      title: View repository
      icon: github
    - url: https://sonarcloud.io/summary/overall?id=rpa-mit-payment-generator
      title: SonarCloud Analysis
    - url: https://snyk.io/test/github/DEFRA/rpa-mit-payment-generator
      title: Snyk Analysis
  tags:
    - dotnet
    - back-end
    - service-bus
    - storage-account
    - application-insights
spec:
  type: backend
  lifecycle: alpha
  owner: "group:default/lap-mit"
  system: "system:default/lap-mit-system"
  dependsOn:
    - "resource:default/rpa-mit-event-storage-queue"
    - "resource:default/rpa-mit-payment-storage-queue"
    - "resource:default/rpa-mit-payment-queue"
    - "resource:default/ADPINFAI01"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rpa-mit-payment-storage-queue
  description: Payment storage queue
  tags:
    - storage-account
    - queue
spec:
  type: message-queue
  owner: "group:default/lap-mit"
  system: "system:default/lap-mit-system"
  dependsOn: 
    - "resource:default/adpinfst01"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rpa-mit-payment-message-queue
  description: Payment service bus message queue
  tags:
    - service-bus
    - queue
spec:
  type: message-queue
  owner: "group:default/lap-mit"
  system: "system:default/lap-mit-system"
  dependsOn: 
    - "resource:default/ADPINFSB01"
  